language: python

python:
  - "3.5"

install:
  - "pip install -r requirements.txt"
  - "pip install flake8"

script:
  - "flake8 --count --ignore=E501,E302,W293,F403,F405,F841 --exclude ./docs,./manage_room/diff_match_patch,./manage_room/migrations,./manage_chat/migrations,./manage.py"
