language: python

python:
  - "3.5"

install:
  - "pip install -r requirements.txt"
  - "pip install flake8"

script:
  - "python secret_key_gen.py"
  - "python manage.py migrate"
  - "flake8 --count --exclude ./docs,./manage_room/diff_match_patch"
