version: '2'
services:
  nginx:
    build: ./nginx
    networks:
      - back
      - front
    ports:
      - "80:80"
    links:
      - daphne
    depends_on:
      - daphne
      - worker
    environment:
       DAPHNE_HOST: daphne
    volumes_from:
      - daphne
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=cnluser
      - POSTGRES_PASSWORD=temporary
      - POSTGRES_DB=codingnightlive
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d:ro
      - ./postgres_db:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    networks:
      - "back"
  redis:
    image: redis
    networks:
      - "back"
    ports:
      - "6379:6379"
  worker:
    build: .
    working_dir: /opt/coding-night-live
    command: bash -c "python manage.py runworker"
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    networks:
      - front
      - back
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
  daphne:
    build: .
    working_dir: /opt/coding-night-live
    command: bash -c "daphne -b 0.0.0.0 -p 8000 coding_night_live.asgi:channel_layer"
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    networks:
     - front
     - back
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
    volumes:
      - /opt/coding-night-live/collected_static
networks:
  front:  # exposed
  back:  # not exposed (DO NOT OPEN THESE PORTS)
