version: '2'
services:
  nginx:
    build: ./nginx
    networks:
      - back
      - front
    ports:
      - "80:8000"
    links:
      - daphne:daphne
  redis:
    image: redis
    networks:
      - "back"
    ports:
      - "6379:6379"
  worker:
    build: .
    working_dir: /opt/coding-night-live
    command: bash -c "python manage.py createsuperuserauto && python manage.py runworker"
    environment:
      - REDIS_HOST=redis
    networks:
      - front
      - back
    depends_on:
      - redis
    links:
      - redis
  daphne:
    build: .
    working_dir: /opt/coding-night-live
    command: bash -c "daphne -b 0.0.0.0 -p 8000 coding_night_live.asgi:channel_layer"
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    networks:
     - front
     - back
    depends_on:
      - redis
    links:
      - redis
networks:
  front:  # exposed
  back:  # not exposed (DO NOT OPEN THESE PORTS)
